- name: Replace Status Module
  ansible.builtin.replace:
      path: /etc/httpd/conf.modules.d/00-base.conf
      regexp: "#LoadModule status_module modules/mod_status.so"
      replace: "LoadModule status_module modules/mod_status.so"

- name: Remove indexes from httpd.conf
  ansible.builtin.replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: "Options Indexes FollowSymLinks"
    replace: "Options FollowSymLinks"

- name: remove welcome.conf
  ansible.builtin.file:
     path: /etc/httpd/conf.d/welcome.conf
     state: absent

- name: Replace LogFormat
  ansible.builtin.replace:
     path: /etc/httpd/conf/httpd.conf
     regexp: '{{item.pre}}'
     replace: '{{item.post}}'
  with_items:
      - [ {pre: 'LogFormat (.*) combined', post: 'LogFormat "%{X-Forwarded-For}i %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined'},
          {pre: 'LogFormat (.*) common', post: 'LogFormat "%a %l %u %t \"%r\" %>s %b" common'}]
  tags: LogFormat

- name: Create 000_default.conf
  copy:
     src: 000_default.conf
     dest: /etc/httpd/conf.d/
  notify: Restart Apache
  tags: copy000

- name: Create Default VH Dir
  ansible.builtin.file:
    path: "/var/www/html/000_default/"
    state: directory
    owner: apache
    group: apache
  notify: Restart Apache
  tags: createvhdirdef
