- name: Install Package RedHat Family
  ansible.builtin.dnf:
     name: "{{yum_package}}"
     state: present
     validate_certs: no
     disable_gpg_check: True
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: Install Package Debian Family
  ansible.builtin.apt:
     name: "{{apt_package}}"
     state: present
  when: ansible_os_family == 'Debian'
  ignore_errors: yes
