- name: Install Apache Package
  import_tasks: install_sw.yml
  tags: installsw

- name: Configure Apache RedHat Family
  import_tasks: httpd_redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: installsw

- name: Configure VH
  import_tasks: vh.yml
  tags: confvh
