- name: Install Package RedHat Family
  ansible.builtin.dnf:
     name: "{{yum_package}}"
     state: present
     validate_certs: no
     disable_gpg_check: True
  ignore_errors: yes

- name: Replace Status Module
  ansible.builtin.replace:
      path: /etc/httpd/conf.modules.d/00-base.conf
      regexp: "#LoadModule status_module modules/mod_status.so"
      replace: "LoadModule status_module modules/mod_status.so"

- name: Remove indexes from httpd.conf
  ansible.builtin.replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: "Options Indexes FollowSymLinks"
    replace: "Options FollowSymLinks"

- name: remove welcome.conf
  ansible.builtin.file:
     path: /etc/httpd/conf.d/welcome.conf
     state: absent

- name: Replace LogFormat
  ansible.builtin.replace:
     path: /etc/httpd/conf/httpd.conf
     regexp: '{{item.pre}}'
     replace: '{{item.post}}'
  with_items:
      - [ {pre: 'LogFormat (.*) combined', post: 'LogFormat "%{X-Forwarded-For}i %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined'},
          {pre: 'LogFormat (.*) common', post: 'LogFormat "%a %l %u %t \"%r\" %>s %b" common'}]
  tags: LogFormat

- name: Create 000_default.conf
  copy:
     src: 000_default.conf
     dest: /etc/httpd/conf.d/
  notify: Restart Apache
  tags: copy000

- name: Create Default VH Dir
  ansible.builtin.file:
    path: "/var/www/html/000_default/"
    state: directory
    owner: apache
    group: apache
  notify: Restart Apache
  tags: createvhdirdef
  
- name: Install virtual host RedHat Family
  template:
     src: virtualhost_redhat.j2
     dest: "/etc/httpd/conf.d/{{item.name}}.conf"
  with_items:
     - "{{virtualhost}}"
  when:
    - item.name |length > 0
  notify: Restart Apache RedHat Family
  tags: vhconf

- name: Add ServerAlias RedHat Family
  lineinfile:
      path: "/etc/httpd/conf.d/{{item.0.name}}.conf"
      insertafter: "^    ServerName"
      line: "    ServerAlias {{item.1}}"
  with_subelements:
    - "{{virtualhost}}"
    - serveralias
  when: item.0.name |length > 0
  notify: Restart Apache RedHat Family
  tags: vhconf

- name: Create dir log RedHat Family
  ansible.builtin.file:
      path: "/var/log/httpd/{{item.name}}"
      state: directory
      owner: root
      group: adm
  with_items:
     - "{{virtualhost}}"
  when:
    - item.name |length > 0
  notify: Restart Apache RedHat Family

- name: Create docroot RedHat Family
  ansible.builtin.file:
      path: "{{item.docroot}}"
      state: directory
      owner: apache
      group: apache
  with_items:
     - "{{virtualhost}}"
  when:
    - item.name |length > 0
  notify: Restart Apache RedHat Family

